config/routes.rb
Rails.application.routes.draw do

  get 'welcome/login'
  get 'welcome/callback'
  get 'logout' => 'welcome#destroy', as: 'logout'
  get 'home/index'

  resources :protocolos
  resources :permitidos
  resources :perfils
  resources :logs
  resources :usuarios

  root 'welcome#login'

end

app/models/permitido.rb
class Permitido < ActiveRecord::Base

  belongs_to :usuario
  belongs_to :perfil

end

app/controllers/permitidos_controller.rb
class PermitidosController < ApplicationController

  before_action :set_permitido, only: [:show, :edit, :update, :destroy]

  before_filter 'autenticado?'


  # GET /permitidos
  # GET /permitidos.json
  def index
    @permitidos = Permitido.all
  end

  # GET /permitidos/1
  # GET /permitidos/1.json
  def show
  end

  # GET /permitidos/new
  def new
    @permitido = Permitido.new
  end

  # GET /permitidos/1/edit
  def edit
  end

  # POST /permitidos
  # POST /permitidos.json
  def create
    @permitido = Permitido.new(permitido_params)

    respond_to do |format|
      if @permitido.save
        addlog("Deu permissão a um usuário")
        format.html { redirect_to @permitido, notice: 'Permissão criada com sucesso.' }
        format.json { render :show, status: :created, location: @permitido }
      else
        format.html { render :new }
        format.json { render json: @permitido.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /permitidos/1
  # PATCH/PUT /permitidos/1.json
  def update
    respond_to do |format|
      if @permitido.update(permitido_params)
        addlog("Atualizou a permissão de um usuário")
        format.html { redirect_to @permitido, notice: 'Permissão atualizada com sucesso.' }
        format.json { render :show, status: :ok, location: @permitido }
      else
        format.html { render :edit }
        format.json { render json: @permitido.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /permitidos/1
  # DELETE /permitidos/1.json
  def destroy
    @permitido.destroy
    addlog("Negou permissão de um usuário")
    respond_to do |format|
      format.html { redirect_to permitidos_url, notice: 'Permissão apagada com sucesso' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_permitido
      @permitido = Permitido.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def permitido_params
      params.require(:permitido).permit(:usuario_id, :perfil_id)
    end
end

app/views/permitidos/_form.html.erb
<%= form_for(@permitido) do |f| %>
  <% if @permitido.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@permitido.errors.count, "error") %> prohibited this permitido from being saved:</h2>

      <ul>
      <% @permitido.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="field">
      <%= f.label :usuario_id, "Usuário" %><br>
      <%= f.select("usuario_id", Usuario.all.collect {|l| [ l.nomeUsuario, l.id ] })  %>
    </div>

    <div class="field">
      <%= f.label :perfil_id, "Perfil" %><br>
      <%= f.select("perfil_id", Perfil.all.collect {|l| [ l.tipo, l.id ] })  %>
    </div>

  <div class="actions">
    <%= f.submit "Salvar", class:"btn btn-primary active" %>
  </div>
<% end %>

app/views/permitidos/edit.html.erb
<h1>Editar Permitido</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @permitido, class: "btn btn-primary active" %> |
<%= link_to 'Voltar', permitidos_path, class: "btn btn-default" %>

app/views/permitidos/index.html.erb
<script type="text/javascript">
    $(document).ready(function() {
        $('#permitido').dataTable ({
            "iDisplayLength": 10, <!-- 10 registros por pagina -->
            "bPaginate": true,    <!-- Paginação  -->
            "sPaginationType":"full_numbers",   <!-- Opção de mostrar numeros por pagina (1,2,3...) -->
            "bJQueryUI":true,
            "bLengthChange":false, <!-- Tira a opção de escolher quantos registros devem aoarecer por paagina -->
            "ordering":     false,  <!-- Tira os links de ordenação de cada coluna -->
            "aaSorting":    [],  <!-- Determina que a ordenação nao seguira nenhuma coluna (por estar vazio). -->
            "oLanguage": { <!-- Inicia a tradução dos itens da tela -->
                "sInfo":              "Mostrando de _START_ até _END_ de _TOTAL_ registros",
                "sInfoFiltered":      "Filtrado de _MAX_ registros no total",
                "sInfoEmpty":         "Sem resultados",
                "sZeroRecords":       "Sem resultados",
                "sSearch":            "Buscar",
                "oPaginate": {
                    "sFirst":         "Primeiro",
                    "sPrevious":      "Anterior",
                    "sNext":          "Próximo",
                    "sLast":          "Ultimo"
                }
            }
        })
    })
</script>

<h1>Permissões</h1>

<table class="table table-bordered display" id="permitido">
  <thead>
    <tr>
      <th>Usuário</th>
      <th>Perfil</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @permitidos.each do |permitido| %>
      <tr>
        <td><%= permitido.usuario.nomeUsuario %></td>
        <td><%= permitido.perfil.tipo %></td>
        <td class="text-center"><%= link_to 'Mostrar', permitido, class: "btn btn-default" %></td>
        <td class="text-center"><%= link_to 'Editar', edit_permitido_path(permitido), class: "btn btn-primary active" %></td>
        <td class="text-center"><%= link_to 'Apagar', permitido, method: :delete, data: { confirm: 'Você tem certeza?' }, class: "btn btn-danger active" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Adicionar permissão', new_permitido_path, class: "btn btn-primary active" %>

app/views/permitidos/new.html.erb
<h1>Adicionar permissão</h1>

<%= render 'form' %>

<%= link_to 'Voltar', permitidos_path, class: "btn btn-default" %>

app/views/permitidos/show.html.erb
<p>
  <strong>Usuario</strong>
  <%= @permitido.usuario.nomeUsuario %>
</p>

<p>
  <strong>Perfil:</strong>
  <%= @permitido.perfil.tipo %>
</p>


<%= link_to 'Editar', edit_permitido_path(@permitido), class: "btn btn-primary active"  %> |
<%= link_to 'Voltar', permitidos_path, class: "btn btn-default"  %>