config/routes.rb
Rails.application.routes.draw do

  get 'welcome/login'
  get 'welcome/callback'
  get 'logout' => 'welcome#destroy', as: 'logout'
  get 'home/index'

  resources :protocolos
  resources :permitidos
  resources :perfils
  resources :logs
  resources :usuarios

  root 'welcome#login'

end

app/models/protocolo.rb
class Protocolo < ActiveRecord::Base
  belongs_to :usuario
  validates_presence_of :enviar_para
  validates_presence_of :observacao
end

app/controllers/protocolos_controller.rb
class ProtocolosController < ApplicationController
  before_action :set_protocolo, only: [:show, :edit, :update, :destroy]

  before_filter 'autenticado?'

  # GET /protocolos
  # GET /protocolos.json
  def index
    @protocolos = Protocolo.all
    respond_to do |format|
      format.html
      format.pdf { render_protocolos_list(@protocolos) }
      end
  end


  # GET /protocolos/1
  # GET /protocolos/1.json
  def show
  end

  # GET /protocolos/new
  def new
    @protocolo = Protocolo.new

  end

  # GET /protocolos/1/edit
  def edit
  end


  # POST /protocolos
  # POST /protocolos.json
  def create
    @protocolo = Protocolo.new(protocolo_params)
    @protocolo.usuario_id = current_user.id
    if Protocolo.all.count == 0
      @protocolo.codigo_protocolo = 1
    else
      lastprotocolo = Protocolo.last!
      if lastprotocolo.created_at.year < Date.today.year
        @protocolo.codigo_protocolo = 1
        addlog("Ano renovado")
      else
        @protocolo.codigo_protocolo = lastprotocolo.codigo_protocolo + 1
      end
    end
    @protocolo.ano = Date.today.year
    @protocolo.dt_expedicao = Date.today

    respond_to do |format|
      if @protocolo.save
        addlog("Protocolo criado")
        format.html { redirect_to @protocolo, notice: 'Protocolo foi criado.' }
        format.json { render :show, status: :created, location: @protocolo }
      else
        format.html { render :new }
        format.json { render json: @protocolo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /protocolos/1
  # PATCH/PUT /protocolos/1.json
  def update
    respond_to do |format|
      if @protocolo.update(protocolo_params)
        addlog("Protocolo alterado")
        format.html { redirect_to @protocolo, notice: 'Protocolo foi atualizado.' }
        format.json { render :show, status: :ok, location: @protocolo }
      else
        format.html { render :edit }
        format.json { render json: @protocolo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /protocolos/1
  # DELETE /protocolos/1.json
  def destroy
    @protocolo.destroy
    respond_to do |format|
      addlog("Protocolo excluído: " + @protocolo.id.to_s)
      format.html { redirect_to protocolos_url, notice: 'Protocolo foi apagado.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_protocolo
      @protocolo = Protocolo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def protocolo_params
      params.require(:protocolo).permit(:enviar_para, :observacao, :dt_expedicao, :ano, :codigo_protocolo)
    end

     def render_protocolos_list(protocolos)
    protoc = protocolos::Report.new layout: File.join(Rails.root, 'app', 'reports', 'protocolos.tlf')

    protocolos.each do |protocolos|
      report.list.add_row do |row|
        row.values name: protocolos.usuario.nomeUsuario
        row.item(:name).style(:color, 'red') unless protocolos.done?
      end
    end

    send_data report.generate, filename: 'protoc.pdf',
              type: 'application/pdf',
              disposition: 'attachment'
  end
end

app/helpers/protocolos_helper.rb
module ProtocolosHelper
end

app/views/protocolos/_form.html.erb
<%= form_for(@protocolo) do |f| %>
  <% if @protocolo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@protocolo.errors.count, "error") %> prohibited this protocolo from being saved:</h2>

      <ul>
      <% @protocolo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <p>
      <%= f.label :enviar_para %><br />
      <%= f.text_area :enviar_para,
                      :cols=>40,
                      :rows=>10 %>
    </p>
    <p>

      <% if @protocolo.observacao %>
          Assunto
	<span style="padding-left: 5em;">
	<%= text_field_tag 'counter_resumo',0,
                       :readonly=> true,
                       :size=> "5",
                       :value=> "#{500 - @protocolo.observacao.length}" %> caracteres restantes
	</span><br>

      <% else %>
          Assunto
	<span style="padding-left: 5em;">
	<%= text_field_tag 'counter_resumo',0,
                       :readonly=> true,
                       :size=> "5",
                       :value=> "#{500}" %> caracteres restantes
	 </span><br />
      <% end %>

      <%= f.text_area :observacao,
                      :cols=> 40,
                      :rows=> 10,
                      :onkeyup=> "fieldSize(this, counter_resumo, 500)" %>
    </p>


    <%= f.submit 'Salvar' %>

<% end %>

<%= link_to 'Voltar', protocolos_path %>

app/views/protocolos/edit.html.erb
<h1>Editar Protocolo</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @protocolo %>

app/views/protocolos/index.html.erb
<script type="text/javascript">
    $(function() {
        oTable = $('#protocolos').dataTable({
            "iDisplayLength": 15,
            "sPaginationType":"full_numbers",
            "bJQueryUI":true,
            "aaSorting": [[0, "desc"]],
            "bLengthChange":false,
            "oLanguage":{
                "sInfo": "Mostrando de _START_ até _END_ de _TOTAL_ registros",
                "sInfoFiltered": "Filtrado de _MAX_ registros no total",
                "sZeroRecords": "Sem resultados",
                "sInfoEmpty": "",
                "sSearch": "Buscar",
                "oPaginate": {
                    "sFirst": "<<",
                    "sPrevious": "<",
                    "sNext": ">",
                    "sLast": ">>"
                }
            }
        });
    });
</script>


<h2>Protocolos</h2>


<%= link_to 'Criar Novo Protocolo', new_protocolo_path %>
<br>

<table id="protocolos" class="display">
  <thead>
  <tr>
    <th style = display:none>ID</th>
    <th align="left">Código</th>
    <th align="left">Enviar para</th>
    <th align="left">Data de expedição</th>
    <th align="left">Expedidor</th>
    <th align="left">Ações</th>
  </tr>
  </thead>

  <tbody>
  <% @protocolos.each do |protocolos| %>
      <tr>
        <td style = display:none><%= protocolos.id %></td>
        <td><%= protocolos.codigo_protocolo.to_s + "/" + protocolos.created_at.year.to_s %></td>
        <td><%= protocolos.enviar_para %></td>
        <td><%= protocolos.created_at.day.to_s +  "/" + protocolos.created_at.month.to_s  +  "/" + protocolos.created_at.year.to_s %></td>
        <td><%= protocolos.usuario.nomeUsuario %></td>
        <td>
          <%= link_to 'Mostrar', protocolos %>
          <%= link_to 'Editar',edit_protocolo_path(protocolos) %>
          <%= link_to 'Imprimir', protocolo_path(protocolos, format: 'pdf'),target: "_blank"  %>
        </td>
      </tr>

  <% end %>
  </tbody>
</table>

<br>

app/views/protocolos/new.html.erb
<h1>Novo Protocolo</h1>

<%= render 'form' %>

app/views/protocolos/show.html.erb
<p>
  <strong>Enviar para:</strong>
  <%= @protocolo.enviar_para %>
</p>

<p>
  <strong>Observação:</strong>
  <%= @protocolo.observacao %>
</p>


<p>
  <strong>Código protocolo:</strong>
  <%= @protocolo.codigo_protocolo %>
</p>

<%= link_to 'Imprimir', protocolo_path(@protocolo, format: 'pdf'),target: "_blank" %>
<%= link_to 'Editar', edit_protocolo_path(@protocolo) %> |
<%= link_to 'Voltar', protocolos_path %>