config/routes.rb
Rails.application.routes.draw do

  get 'welcome/login'
  get 'welcome/callback'
  get 'logout' => 'welcome#destroy', as: 'logout'
  get 'home/index'

  resources :protocolos
  resources :permitidos
  resources :perfils
  resources :logs
  resources :usuarios

  root 'welcome#login'

end

app/views/usuarios_orig/_form.html.erb
<%= form_for(@usuario) do |f| %>
  <% if @usuario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@usuario.errors.count, "error") %> prohibited this usuario from being saved:</h2>

      <ul>
      <% @usuario.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome, "Nome" %><br>
    <%= f.text_field :nome %>
  </div>
   <div class="field">
    <%= f.label :login, "E-mail" %><br>
    <%= f.text_field :login %>
  </div>
  <div class="field">
    <%= f.label :password, "Senha" %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, "Confirmação de senha" %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit "Salvar" %>
  </div>
<% end %>

app/views/usuarios_orig/edit.html.erb
<h1>Editar Usuário</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @usuario %> |
<%= link_to 'Voltar', usuarios_path %>

app/views/usuarios_orig/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lista de Usuários</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>E-mail</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @usuarios.each do |usuario| %>
      <tr>
        <td><%= usuario.login %></td>
        <td><%= link_to 'Mostrar', usuario %></td>
        </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo Usuário', new_usuario_path %>

app/views/usuarios_orig/new.html.erb
<h1>Novo Usuário</h1>

<%= render 'form' %>

<%= link_to 'Voltar', usuarios_path %>

app/views/usuarios_orig/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @usuario.nome %>
</p>

<p>
  <strong>E-mail:</strong>
  <%= @usuario.login %>
</p>

<p>

<% if current_user.id == @usuario.id %>
    <%= link_to 'Editar', edit_usuario_path(@usuario) %>
<% end %>
<br>
<%= link_to 'Voltar', usuarios_path %>